backend:
  name: github
  repo: meska-moc/meska-moc
  branch: main
site_url: https://meska-moc.netlify.app

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tytuł", name: "title", widget: "string", required: true, hint: "Podaj tytuł artykułu" }
      - { label: "Data publikacji", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true, hint: "Wybierz datę publikacji" }
      - { label: "Obrazek", name: "image", widget: "image", required: true, hint: "Dodaj obrazek w formacie PNG lub JPG" }
      - { label: "Treść", name: "body", widget: "markdown", required: true, hint: "Wprowadź treść artykułu w formacie Markdown" }

  - name: "spotkania"
    label: "Spotkania"
    folder: "posts/spotkania"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nazwa wydarzenia", name: "title", widget: "string", required: true, hint: "Podaj nazwę wydarzenia" }
      - { label: "Data", name: "date", widget: "datetime", format: "YYYY-MM-DD", required: true, hint: "Wybierz datę wydarzenia" }
      - { label: "Opis", name: "body", widget: "markdown", required: true, hint: "Dodaj opis wydarzenia w formacie Markdown" }
publish_mode: editorial_workflow
